# Generated by Django 5.1.3 on 2024-11-28 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='google_maps',
            field=models.URLField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
