# Generated by Django 5.1.3 on 2024-11-28 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_location_google_maps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='google_maps',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
