# Generated by Django 5.1.3 on 2024-11-22 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_remove_wineitem_restaurant_wineitem_restaurants_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinkitem',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='wineitem',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
